# Generated by Django 5.1.7 on 2026-09-13 20:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='опис')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='назва')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адреса')),
            ],
            options={
                'verbose_name': 'локація',
                'verbose_name_plural': 'локації',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_number', models.CharField(db_index=True, max_length=50, verbose_name='інвентарний номер')),
                ('name', models.CharField(max_length=255, verbose_name='назва')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True, verbose_name='виробник')),
                ('model_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='модель')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='серійний номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата придбання')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='гарантія до')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('faulty', 'Несправне'), ('in_repair', 'У ремонті'), ('decommissioned', 'Списане')], default='active', max_length=20, verbose_name='статус')),
                ('inspection_interval_days', models.PositiveIntegerField(default=180, verbose_name='інтервал оглядів (днів)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='примітка')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='закріплено за')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.category', verbose_name='категорія')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.location', verbose_name='локація')),
            ],
            options={
                'verbose_name': 'historical обладнання',
                'verbose_name_plural': 'historical обладнання',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='інвентарний номер')),
                ('name', models.CharField(max_length=255, verbose_name='назва')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True, verbose_name='виробник')),
                ('model_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='модель')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='серійний номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата придбання')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='гарантія до')),
                ('status', models.CharField(choices=[('active', 'Активне'), ('faulty', 'Несправне'), ('in_repair', 'У ремонті'), ('decommissioned', 'Списане')], default='active', max_length=20, verbose_name='статус')),
                ('inspection_interval_days', models.PositiveIntegerField(default=180, verbose_name='інтервал оглядів (днів)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='примітка')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL, verbose_name='закріплено за')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='apps.category', verbose_name='категорія')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='apps.location', verbose_name='локація')),
            ],
            options={
                'verbose_name': 'обладнання',
                'verbose_name_plural': 'обладнання',
                'ordering': ['inventory_number'],
            },
        ),
    ]
