# Generated by Django 5.1.7 on 2026-09-13 20:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='опис')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('resolved', 'Вирішена'), ('closed', 'Закрита')], default='new', max_length=20, verbose_name='статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='дата вирішення')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='рішення')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='призначено')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='apps.equipment', verbose_name='обладнання')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='повідомив')),
            ],
            options={
                'verbose_name': 'заявка на несправність',
                'verbose_name_plural': 'заявки на несправність',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата проведення')),
                ('condition', models.CharField(choices=[('good', 'Добре'), ('satisfactory', 'Задовільно'), ('poor', 'Погано')], default='good', max_length=20, verbose_name='стан')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментар')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='apps.equipment', verbose_name='обладнання')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='виконав')),
            ],
            options={
                'verbose_name': 'огляд',
                'verbose_name_plural': 'огляди',
                'ordering': ['-performed_at'],
            },
        ),
    ]
