# Generated by Django 5.1.7 on 2026-09-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_groups_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalequipment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Історія обладнання', 'verbose_name_plural': 'Історія обладнання'},
        ),
    ]
